@startuml
'https://plantuml.com/sequence-diagram

class App{
    main()
    start()
}

class AppController{
    - ArraList
}

class menuController{

}

javafx.Application <|-- App

App -  AppController
AppController - menuController
@enduml